default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 3 } %>

development:
  <<: *default
  database: ai_cv_development

test:
  <<: *default
  database: ai_cv_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
